[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.5",
    "httpx>=0.27.2",
    "pydantic>=2.10.1",
    "pytest>=8.3.3",
    "ruff>=0.7.4",
]
